language: go

go:
  - "1.10"

before_install:
  - go get -t -v ./...
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - gometalinter --tests --deadline=60s

after_success:
  - bash <(curl -s https://codecov.io/bash)
