jobs:
  include:
    # Build and test the go code.
    - language: go

      go: "1.10"

      before_install:
        - go get github.com/alecthomas/gometalinter
        - gometalinter --install

      install:
        # We can't use the default `go get -t -v ./...` because that breaks
        # when it sees `docker/modules.go`.
        - go get -t -v .

      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic
        - gometalinter --tests --deadline=60s

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    # Build the docker image.
    - sudo: required
      group: trusty_latest
      language: python
      services:
        - docker
      env:
        - IMAGE=praekeltfoundation/logspout-sumologic
        - REGISTRY_USER=praekeltorgdeploy
        - secure: pEOV9lQoxvCCWrDn+XiCkhMTPULJ9G2cFPr229n6YA6v8XLeC8jsfGJMmXtgdczPK79q6nnfZEr1EGZDcAK2dbkHGowkIXo096io65tCjsydUn2rGyajizePWXz4ycENIKeWcAxA7eUVhxRoRVY5Q4aTCHM+ZGzalBqdxFKdBDOEvok3FuDyLnwUZjVuM748295FGHbE/lz30NORfgAIkuWOEG16PlaIYutcnOWYHVLmvwfEkkZ/77eCWwymafZ2RNYn/l4WNr5W6mC4OqCDb90+tQ/o+VJyhJzy8FNzbZUecs7PXKKr8uzZhS6+L6KgwxLXRS4WOOxvTAKV3u9x7ByH8prvLWdhxuhfSSRcDFVGmrMWry/5WcSBmBtqORcbTo0ahv6eoR+C8IHZbZ2Hz5Oi0Y+OLFwXOcxF4wPabxJkQyeXyM+RgQ19l69TCi086ez3KHP38tUEr1owbAVYTM9BhjAQf5XBZchwNQqpyXzJsiueDEoelBSDfnSaqWR+F2SYXB/liuUBw9Z9W8nTNgjFb3GIyv4rxzsHPLn94sswc09tPsPSNabxVC+0/pHqXMTpzQ+NsyffXIjYifda+qWugCbLP60Vp0WWr+cE7TZwm42LOjmKOCV0ATtQNityfmxvdNLeSlX1nBxfv3mbJTybvZI8bQF1uOb456cqcI8=
      install: []
      before_script:
        - cd docker
        - export version="$(awk '$2 == "LOGSPOUT_SUMOLOGIC_VERSION" { print $3; exit }' Dockerfile | cut -d'~'
          -f1)"
        - export logspout_version="$(awk '$2 == "LOGSPOUT_VERSION" { print $3; exit }' Dockerfile | cut -d'~'
          -f1)"
        - docker pull "$IMAGE" || true
      script:
        - docker build --pull --cache-from "$IMAGE" -t "$IMAGE" .
      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
      deploy:
        provider: script
        script: $TRAVIS_BUILD_DIR/docker/deploy.sh
        on:
          branch: master
